Review.delete_all
User.delete_all
Post.delete_all

u1 = User.create(:id=>200, :name => 'Elizabeth',  :email=> "ehramberg@gmail.com", :password=> "foobar", :password_confirmation=> "foobar", :about_me=> "Four loko whatever ugh quinoa salvia, mustache polaroid cardigan squid kogi Bushwick pop-up. Ugh Schlitz +1, flexitarian paleo master cleanse cornhole distillery whatever Williamsburg PBR 3 wolf moon tofu Vice brunch. Cliche mixtape Schlitz, +1 paleo flannel 8-bit organic craft beer Shoreditch beard Portland Echo Park. Odd Future food truck plaid, hella pug Blue Bottle Schlitz lomo street art fanny pack chia viral. Pour-over banh mi lomo organic selfies hashtag. Chillwave synth Wes Anderson Williamsburg post-ironic readymade, cliche Echo Park fixie YOLO photo booth Blue Bottle. Readymade distillery Neutra normcore, banjo Vice pug PBR&B authentic.

Tousled craft beer raw denim plaid distillery kitsch Helvetica beard, wolf chambray. Kale chips fap mlkshk, seitan leggings direct trade street art polaroid Echo Park Wes Anderson bitters meh. Flexitarian mixtape cliche, Blue Bottle chillwave single-origin coffee kale chips sartorial 8-bit Etsy skateboard +1. McSweeney's authentic fingerstache post-ironic bespoke. Try-hard semiotics Blue Bottle four loko. Brooklyn Shoreditch craft beer Schlitz. Blog Shoreditch asymmetrical, mlkshk selfies next level pug seitan PBR&B meh typewriter wayfarers hella narwhal.")

u2 = User.create(:id=>205, :name => 'Markus',  :email=> "mguehrs@gmail.com", :password=> "foobar", :password_confirmation=> "foobar", :about_me=> "Letterpress four loko banjo scenester. Williamsburg banjo banh mi pork belly ethnic, cliche Carles. XOXO sustainable roof party, mixtape VHS hashtag meggings Banksy letterpress wayfarers kitsch gluten-free. Williamsburg sustainable kitsch biodiesel Wes Anderson, occupy flannel craft beer viral raw denim 3 wolf moon. Actually fap bicycle rights 90's cred. Ethnic dreamcatcher chia shabby chic, master cleanse disrupt put a bird on it beard next level chillwave meh scenester letterpress. Schlitz locavore polaroid, try-hard street art typewriter YOLO scenester art party mumblecore occupy.

Church-key mixtape fingerstache, small batch Pitchfork street art ennui chillwave before they sold out. 90's kale chips authentic, Pitchfork Thundercats brunch twee Williamsburg mlkshk cliche Truffaut Schlitz sriracha American Apparel synth. Fap food truck readymade fashion axe mixtape, Portland plaid Bushwick sartorial lo-fi typewriter bespoke. Flannel organic squid, church-key viral jean shorts sriracha Banksy pop-up VHS. Salvia drinking vinegar literally, gluten-free fashion axe ennui YOLO farm-to-table. Irony American Apparel authentic aesthetic master cleanse, bespoke ethnic keffiyeh kogi you probably haven't heard of them Cosby sweater Odd Future bicycle rights gluten-free. You probably haven't heard of them chia direct trade Odd Future pour-over.

Odd Future raw denim Shoreditch deep v. Quinoa Neutra plaid, hoodie Brooklyn butcher PBR&B ugh actually mumblecore photo booth cray. Brooklyn vinyl locavore, Echo Park cliche Vice authentic bespoke art party. Sustainable Bushwick occupy Blue Bottle, Austin Carles typewriter readymade tote bag Godard Wes Anderson. Dreamcatcher biodiesel Williamsburg, 90's scenester plaid XOXO. Forage Tumblr squid letterpress organic skateboard, whatever single-origin coffee Neutra semiotics PBR Schlitz flexitarian cray. Pour-over stumptown chillwave meggings jean shorts, actually farm-to-table.

XOXO Godard kogi Pinterest, biodiesel quinoa Portland Bushwick beard PBR&B trust fund scenester ugh. Meh church-key put a bird on it viral. Church-key Truffaut freegan, mumblecore Helvetica quinoa selfies cornhole Cosby sweater retro VHS disrupt Bushwick. Keffiyeh pickled selvage +1 organic, Thundercats umami Neutra. Normcore before they sold out scenester ennui, High Life Neutra Williamsburg fanny pack Marfa literally. Hella salvia iPhone, squid fanny pack letterpress ennui meh forage Etsy. 90's Austin biodiesel Bushwick, cardigan next level Vice locavore.")


p1 = Post.create(:id=>502, :user_id=>200, :title=>"This is the second user's post", :text=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque molestie semper pretium. Nam non neque ipsum. Nulla facilisi. In in felis quis est suscipit commodo ac eget elit. Suspendisse tincidunt odio id massa vehicula, vitae feugiat velit facilisis. Praesent vel porttitor metus. Aliquam erat volutpat. Fusce tempus turpis metus, eu dapibus mauris eleifend vel. Ut ultricies sollicitudin pellentesque.

Sed aliquam tempor augue sed tristique. Donec ornare sollicitudin magna in venenatis. Integer orci arcu, condimentum eget nisl non, interdum malesuada nibh. Mauris vehicula ornare nulla, eget hendrerit tortor pulvinar ut. Ut a dictum enim, sed tristique dui. Pellentesque cursus ipsum ac porta tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce ut odio non turpis mollis tristique. Ut ultrices sagittis faucibus. Vestibulum sodales nunc odio, id porttitor tellus mollis ac. Praesent velit nunc, tincidunt id elit non, gravida dapibus erat. Integer eleifend cursus rutrum. In hac habitasse platea dictumst. Nulla nunc justo, dapibus ut laoreet at, aliquet in risus. Donec dictum est id erat iaculis semper.

")

p2 = Post.create(:id=>200, :user_id=>205, :title=>"Wonderful post", :text=> "Four loko whatever ugh quinoa salvia, mustache polaroid cardigan squid kogi Bushwick pop-up. Ugh Schlitz +1, flexitarian paleo master cleanse cornhole distillery whatever Williamsburg PBR 3 wolf moon tofu Vice brunch. Cliche mixtape Schlitz, +1 paleo flannel 8-bit organic craft beer Shoreditch beard Portland Echo Park. Odd Future food truck plaid, hella pug Blue Bottle Schlitz lomo street art fanny pack chia viral. Pour-over banh mi lomo organic selfies hashtag. Chillwave synth Wes Anderson Williamsburg post-ironic readymade, cliche Echo Park fixie YOLO photo booth Blue Bottle. Readymade distillery Neutra normcore, banjo Vice pug PBR&B authentic.

Tousled craft beer raw denim plaid distillery kitsch Helvetica beard, wolf chambray. Kale chips fap mlkshk, seitan leggings direct trade street art polaroid Echo Park Wes Anderson bitters meh. Flexitarian mixtape cliche, Blue Bottle chillwave single-origin coffee kale chips sartorial 8-bit Etsy skateboard +1. McSweeney's authentic fingerstache post-ironic bespoke. Try-hard semiotics Blue Bottle four loko. Brooklyn Shoreditch craft beer Schlitz. Blog Shoreditch asymmetrical, mlkshk selfies next level pug seitan PBR&B meh typewriter wayfarers hella narwhal.")



r1 = Review.create(:post_id=>500, :user_id=>200, :title=> "What a great post", :text=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus nibh, sagittis vel enim id, faucibus imperdiet lectus. Vivamus vehicula placerat odio. Maecenas nec laoreet dui. Integer tincidunt felis massa. Mauris et mi arcu. Nunc sit amet risus non nibh ultrices lacinia et ut eros. In erat felis, dignissim a odio eu, semper tincidunt sem.

Phasellus dolor odio, vulputate et nunc vitae, ultrices tincidunt mauris. Donec augue tortor, viverra eu metus id, mollis tincidunt tortor. Phasellus scelerisque neque in rutrum congue. Aliquam erat volutpat. Mauris eleifend posuere risus. Vestibulum aliquet erat ut nulla facilisis fringilla. Donec ut risus ullamcorper, gravida metus sit amet, vehicula ipsum. Sed et felis tellus. Nam semper turpis ac lectus blandit dapibus. Ut tempor, ligula a pellentesque tristique, felis ante dignissim quam, sit amet iaculis orci dui ultrices leo. Morbi bibendum molestie accumsan. Nunc blandit pellentesque velit nec porta. Sed facilisis, dui vitae ullamcorper tempus, ante purus congue neque, nec gravida nisl quam eget augue. Maecenas consequat, dolor varius vehicula fermentum, purus orci ultrices lacus, fermentum semper diam odio in massa.

Donec lobortis, ante ut vulputate tempus, metus massa commodo tellus, at ullamcorper metus justo eget justo. Aliquam dictum augue urna, et convallis sem vestibulum at. Sed interdum enim orci, ac malesuada purus egestas sed. Mauris pellentesque, ligula dictum aliquam faucibus, neque neque imperdiet magna, id malesuada orci dolor sit amet lectus. Phasellus tortor mi, luctus sed quam vel, iaculis aliquet lectus. Suspendisse ultricies tristique sapien sit amet suscipit. Vestibulum tempus sem vitae hendrerit porta. Aenean semper leo libero, eget auctor lorem porta in. Morbi quis elit mauris. Pellentesque adipiscing mattis lorem, at vehicula magna ultricies vel. Quisque convallis justo libero, fermentum sodales nunc ultrices quis. Donec tincidunt mauris fermentum aliquet tincidunt. Ut placerat volutpat varius. Duis mollis, ante nec auctor vehicula, enim justo pellentesque enim, convallis ultrices felis magna sit amet lorem. Praesent ut metus ultrices, eleifend velit eget, pharetra nulla.

", :score=>4)

r3 = Review.create(:post_id=>502, :user_id=>205, :title=>"Post review", :text=>"Mustache 8-bit bicycle rights before they sold out, pop-up four loko Blue Bottle pug Odd Future raw denim normcore XOXO. XOXO keffiyeh ugh pour-over Williamsburg forage. Freegan tofu messenger bag church-key lomo direct trade. Intelligentsia whatever bitters occupy, narwhal cliche semiotics disrupt +1 bespoke gastropub Wes Anderson craft beer biodiesel viral. Four loko put a bird on it Portland hella, drinking vinegar single-origin coffee sustainable yr synth YOLO chambray retro bespoke letterpress. Austin cornhole asymmetrical, cardigan irony freegan shabby chic Truffaut pork belly lo-fi actually farm-to-table Wes Anderson Cosby sweater ethnic. Stumptown four loko dreamcatcher XOXO Schlitz, post-ironic kale chips leggings ugh art party trust fund Brooklyn polaroid.

Sustainable vegan kogi keffiyeh, Vice deep v fashion axe food truck post-ironic jean shorts flannel. Banksy selfies Austin, trust fund PBR semiotics gentrify Echo Park retro. Master cleanse occupy photo booth asymmetrical gastropub, Truffaut vinyl. Retro street art freegan, beard Truffaut authentic ethical XOXO. 90's 8-bit Tonx deep v aesthetic hashtag. Fanny pack actually master cleanse occupy. Tumblr Truffaut Etsy, Neutra PBR&B Portland 90's authentic jean shorts Helvetica umami meggings chia beard street art.", :score=>4)

r4 = Review.create(:post_id=>200, :user_id=>205, :title=>"Post review", :text=>"Mustache 8-bit bicycle rights before they sold out, pop-up four loko Blue Bottle pug Odd Future raw denim normcore XOXO. XOXO keffiyeh ugh pour-over Williamsburg forage. Freegan tofu messenger bag church-key lomo direct trade. Intelligentsia whatever bitters occupy, narwhal cliche semiotics disrupt +1 bespoke gastropub Wes Anderson craft beer biodiesel viral. Four loko put a bird on it Portland hella, drinking vinegar single-origin coffee sustainable yr synth YOLO chambray retro bespoke letterpress. Austin cornhole asymmetrical, cardigan irony freegan shabby chic Truffaut pork belly lo-fi actually farm-to-table Wes Anderson Cosby sweater ethnic. Stumptown four loko dreamcatcher XOXO Schlitz, post-ironic kale chips leggings ugh art party trust fund Brooklyn polaroid.

Sustainable vegan kogi keffiyeh, Vice deep v fashion axe food truck post-ironic jean shorts flannel. Banksy selfies Austin, trust fund PBR semiotics gentrify Echo Park retro. Master cleanse occupy photo booth asymmetrical gastropub, Truffaut vinyl. Retro street art freegan, beard Truffaut authentic ethical XOXO. 90's 8-bit Tonx deep v aesthetic hashtag. Fanny pack actually master cleanse occupy. Tumblr Truffaut Etsy, Neutra PBR&B Portland 90's authentic jean shorts Helvetica umami meggings chia beard street art.", :score=>4)
