Review.delete_all
User.delete_all
Post.delete_all

u1 = User.create(:id=>100, :name=>'Diane Shen', :email=>'ds@gmail.com', :password=> "foobar", :password_confirmation=> "foobar", :about_me=> "Meh twee Godard, iPhone pork belly asymmetrical umami. Art party street art yr, hashtag ethnic mustache swag polaroid. Freegan pour-over aesthetic, gastropub PBR&B Williamsburg shabby chic banjo paleo viral. Leggings keytar PBR&B, tousled Helvetica artisan fixie jean shorts shabby chic vinyl biodiesel Tonx kogi. Kitsch retro PBR&B kale chips yr chia, stumptown slow-carb ethnic readymade Thundercats McSweeney's drinking vinegar disrupt you probably haven't heard of them. Kale chips cornhole asymmetrical readymade messenger bag, scenester fingerstache Tumblr master cleanse 90's squid synth chillwave slow-carb. Cray Echo Park plaid, synth typewriter normcore fingerstache street art Vice disrupt artisan viral Intelligentsia Cosby sweater twee.")
u2 = User.create(:id=>200, :name => 'Markus',  :email=> "mguehrs@gmail.com", :password=> "foobar", :password_confirmation=> "foobar", :about_me=> "Letterpress four loko banjo scenester. Williamsburg banjo banh mi pork belly ethnic, cliche Carles. XOXO sustainable roof party, mixtape VHS hashtag meggings Banksy letterpress wayfarers kitsch gluten-free. Williamsburg sustainable kitsch biodiesel Wes Anderson, occupy flannel craft beer viral raw denim 3 wolf moon. Actually fap bicycle rights 90's cred. Ethnic dreamcatcher chia shabby chic, master cleanse disrupt put a bird on it beard next level chillwave meh scenester letterpress. Schlitz locavore polaroid, try-hard street art typewriter YOLO scenester art party mumblecore occupy.

Church-key mixtape fingerstache, small batch Pitchfork street art ennui chillwave before they sold out. 90's kale chips authentic, Pitchfork Thundercats brunch twee Williamsburg mlkshk cliche Truffaut Schlitz sriracha American Apparel synth. Fap food truck readymade fashion axe mixtape, Portland plaid Bushwick sartorial lo-fi typewriter bespoke. Flannel organic squid, church-key viral jean shorts sriracha Banksy pop-up VHS. Salvia drinking vinegar literally, gluten-free fashion axe ennui YOLO farm-to-table. Irony American Apparel authentic aesthetic master cleanse, bespoke ethnic keffiyeh kogi you probably haven't heard of them Cosby sweater Odd Future bicycle rights gluten-free. You probably haven't heard of them chia direct trade Odd Future pour-over.

Odd Future raw denim Shoreditch deep v. Quinoa Neutra plaid, hoodie Brooklyn butcher PBR&B ugh actually mumblecore photo booth cray. Brooklyn vinyl locavore, Echo Park cliche Vice authentic bespoke art party. Sustainable Bushwick occupy Blue Bottle, Austin Carles typewriter readymade tote bag Godard Wes Anderson. Dreamcatcher biodiesel Williamsburg, 90's scenester plaid XOXO. Forage Tumblr squid letterpress organic skateboard, whatever single-origin coffee Neutra semiotics PBR Schlitz flexitarian cray. Pour-over stumptown chillwave meggings jean shorts, actually farm-to-table.

XOXO Godard kogi Pinterest, biodiesel quinoa Portland Bushwick beard PBR&B trust fund scenester ugh. Meh church-key put a bird on it viral. Church-key Truffaut freegan, mumblecore Helvetica quinoa selfies cornhole Cosby sweater retro VHS disrupt Bushwick. Keffiyeh pickled selvage +1 organic, Thundercats umami Neutra. Normcore before they sold out scenester ennui, High Life Neutra Williamsburg fanny pack Marfa literally. Hella salvia iPhone, squid fanny pack letterpress ennui meh forage Etsy. 90's Austin biodiesel Bushwick, cardigan next level Vice locavore.")

p1 = Post.create(:id=>500, :user_id=>100, :title=>"This is a post", :text=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi nec velit feugiat lobortis. Etiam consequat ligula eu nisl imperdiet, sed tincidunt odio malesuada. Fusce hendrerit eu turpis non convallis. Fusce vel ipsum dignissim, ultricies risus id, molestie ligula. Mauris molestie est massa, non placerat diam facilisis vitae. Donec euismod mattis odio eu dignissim. In ut leo non est feugiat ullamcorper non convallis mi. Vestibulum velit ipsum, aliquam et iaculis quis, imperdiet non lectus. Morbi iaculis massa a tincidunt mattis. Nunc id risus turpis. Donec sed risus libero. Nulla at vehicula ligula, ac malesuada diam. Duis eu laoreet sapien.

Suspendisse ut quam quis nulla rhoncus tempus a a sapien. Duis nulla enim, consectetur eget lacinia quis, lacinia eu enim. Nulla eu tempor sem. Curabitur iaculis elit eu velit interdum, ac eleifend libero feugiat. Maecenas et quam eget nibh adipiscing laoreet. Donec vehicula nisi ligula, et dignissim est semper eu. Proin ut justo congue, convallis magna id, feugiat tellus. Morbi venenatis enim quis ullamcorper cursus. Pellentesque et est hendrerit, ultrices erat non, venenatis urna. Integer placerat mi mi, nec sodales ipsum volutpat facilisis.

Curabitur feugiat lobortis eros, consequat tempor eros. Curabitur quis tellus sem. Etiam aliquam consectetur lectus ut faucibus. Quisque nunc ligula, consequat nec tristique vitae, varius in eros. Ut eleifend ligula eget aliquam sodales. Suspendisse dignissim semper nisi a lacinia. Fusce ac mattis magna, in commodo est. Morbi bibendum sodales fermentum. Suspendisse vitae quam et enim rhoncus vehicula. Sed non porta dui, eget laoreet odio. Maecenas accumsan nunc id diam posuere gravida.

Aenean et pulvinar sapien. Praesent ullamcorper nisl diam, a tristique turpis pulvinar et. Vivamus non aliquam orci, a rutrum turpis. Sed sapien sapien, varius non pellentesque sit amet, eleifend eu ante. Proin aliquam neque eget sollicitudin tincidunt. Phasellus vel consectetur risus, a placerat dolor. Praesent dapibus tellus vitae dui facilisis luctus tempus in ante. Vestibulum quis dictum tortor, ac euismod sapien.

Sed vel congue neque, pharetra pharetra mauris. Morbi sollicitudin dictum enim, non tempor sem. Quisque posuere diam vel tempor faucibus. Donec semper consectetur erat id rhoncus. Maecenas sagittis quam quis dui condimentum mollis eu vel tellus. Phasellus quis bibendum justo. In vel lacinia tortor, non ornare lectus. In pharetra magna nisi, a accumsan augue viverra a. Praesent vitae erat euismod, sagittis magna quis, porttitor mauris. Praesent pretium scelerisque pharetra. Nunc gravida placerat tortor nec tempor. Aenean ac convallis justo. Sed est magna, lacinia non tellus nec, sollicitudin pellentesque purus. Nullam tristique mi nec lacus vestibulum, non sollicitudin dui pellentesque. Fusce vel felis tellus. Etiam auctor fermentum diam, ac facilisis mauris commodo lacinia.")
p2 = Post.create(:id=>501, :user_id=>100, :title=>"This is my second post", :text=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis convallis nulla sit amet porta luctus. Suspendisse luctus dignissim odio, et lacinia arcu commodo semper. Sed interdum urna eu posuere elementum. Ut vel nibh ac magna condimentum cursus. Nam accumsan aliquet felis nec fringilla. Ut ut semper lacus. Duis porta ut purus a ultricies. Nullam faucibus condimentum malesuada. Etiam fringilla augue at bibendum sagittis. Praesent at felis at tortor dictum tincidunt id et lectus. Curabitur sit amet ante a diam eleifend fringilla. Nam commodo sollicitudin sem, a congue elit facilisis non. Mauris sed justo aliquam, mattis orci sed, placerat enim. In at viverra sem, sit amet tempus dui. Cras sodales urna quis est lacinia condimentum.

Nam dui dolor, porta ac magna ut, mattis adipiscing neque. Nam ac hendrerit magna, eu elementum nisi. Donec a magna massa. Integer vehicula felis enim, a molestie tellus lobortis sed. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam venenatis ipsum elit, vitae adipiscing justo volutpat at. Aenean nec massa sit amet sapien vehicula vehicula. Ut laoreet interdum eros, sed vehicula elit posuere at. Aenean dui justo, varius tristique convallis accumsan, ultrices quis libero. Nullam eget consequat dui. Nulla sed feugiat nisl. Nunc ultricies vitae massa sed iaculis. Suspendisse id est vitae lectus scelerisque scelerisque. Quisque nec mollis quam, ut euismod erat. Donec pharetra, sem et pretium ultrices, ligula libero rutrum arcu, id vehicula lectus dolor vel tortor. Aliquam scelerisque congue mi id accumsan.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec et iaculis lorem. Fusce lacinia urna metus, eu mollis turpis volutpat sit amet. Mauris et pharetra diam. Nullam suscipit augue augue, quis consequat purus pharetra non. Curabitur aliquet iaculis justo, et mattis mauris imperdiet vel. Ut adipiscing semper dictum. Nulla mattis, risus non posuere mattis, massa felis pellentesque diam, ac cursus nibh eros at libero. Etiam risus erat, imperdiet ut leo ac, congue aliquet lectus.")
p3 = Post.create(:id=>502, :user_id=>200, :title=>"This is the second user's post", :text=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque molestie semper pretium. Nam non neque ipsum. Nulla facilisi. In in felis quis est suscipit commodo ac eget elit. Suspendisse tincidunt odio id massa vehicula, vitae feugiat velit facilisis. Praesent vel porttitor metus. Aliquam erat volutpat. Fusce tempus turpis metus, eu dapibus mauris eleifend vel. Ut ultricies sollicitudin pellentesque.

Sed aliquam tempor augue sed tristique. Donec ornare sollicitudin magna in venenatis. Integer orci arcu, condimentum eget nisl non, interdum malesuada nibh. Mauris vehicula ornare nulla, eget hendrerit tortor pulvinar ut. Ut a dictum enim, sed tristique dui. Pellentesque cursus ipsum ac porta tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce ut odio non turpis mollis tristique. Ut ultrices sagittis faucibus. Vestibulum sodales nunc odio, id porttitor tellus mollis ac. Praesent velit nunc, tincidunt id elit non, gravida dapibus erat. Integer eleifend cursus rutrum. In hac habitasse platea dictumst. Nulla nunc justo, dapibus ut laoreet at, aliquet in risus. Donec dictum est id erat iaculis semper.

")

r1 = Review.create(:post_id=>500, :user_id=>200, :title=> "What a great post", :text=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc risus nibh, sagittis vel enim id, faucibus imperdiet lectus. Vivamus vehicula placerat odio. Maecenas nec laoreet dui. Integer tincidunt felis massa. Mauris et mi arcu. Nunc sit amet risus non nibh ultrices lacinia et ut eros. In erat felis, dignissim a odio eu, semper tincidunt sem.

Phasellus dolor odio, vulputate et nunc vitae, ultrices tincidunt mauris. Donec augue tortor, viverra eu metus id, mollis tincidunt tortor. Phasellus scelerisque neque in rutrum congue. Aliquam erat volutpat. Mauris eleifend posuere risus. Vestibulum aliquet erat ut nulla facilisis fringilla. Donec ut risus ullamcorper, gravida metus sit amet, vehicula ipsum. Sed et felis tellus. Nam semper turpis ac lectus blandit dapibus. Ut tempor, ligula a pellentesque tristique, felis ante dignissim quam, sit amet iaculis orci dui ultrices leo. Morbi bibendum molestie accumsan. Nunc blandit pellentesque velit nec porta. Sed facilisis, dui vitae ullamcorper tempus, ante purus congue neque, nec gravida nisl quam eget augue. Maecenas consequat, dolor varius vehicula fermentum, purus orci ultrices lacus, fermentum semper diam odio in massa.

Donec lobortis, ante ut vulputate tempus, metus massa commodo tellus, at ullamcorper metus justo eget justo. Aliquam dictum augue urna, et convallis sem vestibulum at. Sed interdum enim orci, ac malesuada purus egestas sed. Mauris pellentesque, ligula dictum aliquam faucibus, neque neque imperdiet magna, id malesuada orci dolor sit amet lectus. Phasellus tortor mi, luctus sed quam vel, iaculis aliquet lectus. Suspendisse ultricies tristique sapien sit amet suscipit. Vestibulum tempus sem vitae hendrerit porta. Aenean semper leo libero, eget auctor lorem porta in. Morbi quis elit mauris. Pellentesque adipiscing mattis lorem, at vehicula magna ultricies vel. Quisque convallis justo libero, fermentum sodales nunc ultrices quis. Donec tincidunt mauris fermentum aliquet tincidunt. Ut placerat volutpat varius. Duis mollis, ante nec auctor vehicula, enim justo pellentesque enim, convallis ultrices felis magna sit amet lorem. Praesent ut metus ultrices, eleifend velit eget, pharetra nulla.

", :score=>4)
r2 = Review.create(:post_id=>501, :user_id=>200, :title=>"This is a very good post as well", text:"Bitters Intelligentsia mustache, tote bag bicycle rights readymade Wes Anderson Bushwick deep v iPhone asymmetrical. Locavore lomo mixtape, Vice jean shorts Godard chillwave stumptown keffiyeh whatever art party shabby chic deep v leggings. Tofu cornhole roof party chillwave deep v, single-origin coffee Godard bicycle rights cray retro fashion axe tousled. Four loko readymade actually, church-key art party Tumblr gastropub messenger bag Truffaut. Neutra retro disrupt kitsch 3 wolf moon viral organic, Thundercats hoodie Pitchfork. Put a bird on it ennui Brooklyn skateboard American Apparel locavore, flexitarian gentrify chia retro organic Neutra PBR&B. Deep v raw denim freegan, gastropub cray pour-over small batch fanny pack typewriter trust fund.

Etsy Thundercats wayfarers jean shorts fanny pack hella pickled cray. PBR&B cray squid yr. Tonx fashion axe American Apparel hoodie. Thundercats disrupt DIY forage, ennui meh Portland photo booth. Deep v fixie cray church-key. Brooklyn four loko sustainable PBR authentic, retro kitsch +1 flexitarian seitan mustache Truffaut church-key. Ugh leggings ennui kale chips Banksy.

Mlkshk craft beer literally, pop-up fixie keytar retro hoodie ethnic narwhal. Asymmetrical mlkshk PBR&B, put a bird on it raw denim literally fashion axe skateboard kale chips pickled gluten-free. Literally tousled ennui tofu squid irony DIY PBR&B mixtape High Life. Scenester forage Marfa skateboard. Art party food truck Etsy polaroid. Pug fingerstache freegan mustache, kale chips mumblecore synth jean shorts semiotics Tonx Godard tousled. Schlitz artisan umami, organic twee polaroid VHS selvage.

Yr +1 pour-over, roof party tousled pug Banksy fingerstache blog DIY asymmetrical chia readymade lo-fi. Sriracha ethnic wayfarers hoodie, artisan freegan Bushwick whatever American Apparel. Salvia retro Intelligentsia put a bird on it. Flexitarian PBR roof party, keytar raw denim jean shorts Odd Future trust fund authentic seitan ennui you probably haven't heard of them irony. Artisan butcher whatever Carles Odd Future, shabby chic cornhole DIY Tonx. Cornhole Tonx Truffaut tattooed Blue Bottle, hashtag sartorial normcore Helvetica chambray locavore wayfarers pop-up. Squid cray whatever mixtape, letterpress aesthetic fanny pack 90's slow-carb cardigan Intelligentsia meggings Portland banjo Tonx.", :score=>3)
r3 = Review.create(:post_id=>500, :user_id=>200, :title=>"Post review", :text=>"Mustache 8-bit bicycle rights before they sold out, pop-up four loko Blue Bottle pug Odd Future raw denim normcore XOXO. XOXO keffiyeh ugh pour-over Williamsburg forage. Freegan tofu messenger bag church-key lomo direct trade. Intelligentsia whatever bitters occupy, narwhal cliche semiotics disrupt +1 bespoke gastropub Wes Anderson craft beer biodiesel viral. Four loko put a bird on it Portland hella, drinking vinegar single-origin coffee sustainable yr synth YOLO chambray retro bespoke letterpress. Austin cornhole asymmetrical, cardigan irony freegan shabby chic Truffaut pork belly lo-fi actually farm-to-table Wes Anderson Cosby sweater ethnic. Stumptown four loko dreamcatcher XOXO Schlitz, post-ironic kale chips leggings ugh art party trust fund Brooklyn polaroid.

Sustainable vegan kogi keffiyeh, Vice deep v fashion axe food truck post-ironic jean shorts flannel. Banksy selfies Austin, trust fund PBR semiotics gentrify Echo Park retro. Master cleanse occupy photo booth asymmetrical gastropub, Truffaut vinyl. Retro street art freegan, beard Truffaut authentic ethical XOXO. 90's 8-bit Tonx deep v aesthetic hashtag. Fanny pack actually master cleanse occupy. Tumblr Truffaut Etsy, Neutra PBR&B Portland 90's authentic jean shorts Helvetica umami meggings chia beard street art.", :score=>4)
r4 = Review.create(:post_id=>502, :user_id=>100, :title=> "dskfjkdgjd", :text=>"Cornhole freegan Brooklyn seitan. Retro art party Etsy organic iPhone four loko meh Wes Anderson lo-fi, roof party skateboard salvia forage readymade. Direct trade gluten-free Vice drinking vinegar. Chia Banksy mustache XOXO, banjo craft beer kogi messenger bag tofu. Blue Bottle salvia keffiyeh, VHS sartorial art party single-origin coffee High Life freegan organic farm-to-table Austin. Readymade bespoke American Apparel, whatever Intelligentsia church-key lo-fi literally fanny pack jean shorts irony paleo sartorial aesthetic. Polaroid Shoreditch locavore, organic YOLO typewriter cred 3 wolf moon roof party iPhone kale chips flannel freegan lo-fi.

Jean shorts retro fap, plaid small batch letterpress Neutra. Ethical tousled cardigan meggings High Life post-ironic. Literally farm-to-table hoodie bicycle rights freegan, mustache gentrify distillery keffiyeh mumblecore readymade pork belly forage hashtag locavore. Locavore Portland 8-bit synth small batch cornhole, jean shorts pour-over tattooed church-key craft beer art party sriracha wayfarers. Pitchfork Intelligentsia keffiyeh yr. Vice single-origin coffee banh mi Odd Future Brooklyn selvage, Shoreditch mustache blog fanny pack polaroid. Sartorial tattooed put a bird on it, XOXO DIY mlkshk ennui pickled Godard beard Marfa kitsch asymmetrical cred.

Single-origin coffee pickled forage photo booth Intelligentsia vegan shabby chic tofu. Ugh Tumblr normcore selfies YOLO chillwave viral, letterpress tote bag lo-fi. Shoreditch cred Thundercats, sartorial try-hard meggings DIY butcher cray Truffaut. Flexitarian Tonx Wes Anderson, Helvetica Odd Future organic Godard lo-fi Portland viral authentic Thundercats small batch. Scenester 3 wolf moon Wes Anderson vegan, literally Pitchfork Tonx art party quinoa VHS asymmetrical mixtape narwhal semiotics. Sriracha mumblecore Blue Bottle, post-ironic wolf bicycle rights Brooklyn twee hashtag yr meggings messenger bag. Street art Helvetica fingerstache, PBR&B fap Carles selvage Cosby sweater raw denim sartorial lomo you probably haven't heard of them tofu bitters.j", :score=>1)

